task3 part 1
js-tasks-ru/js-20201211_alexey-b pull request #3
Opened 2020-12-20 17:10 UTC by alekseipeecho

Первая задача не понятна, материала пройденного на курсе явно не хватает для решения, потратил слишком много времени на нее.  Задача с trim добавлю следущим комитом если успею

2020-12-20 17:25 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ gets more.nested.property
- returns undefined for no nested.property
```
```diff
trimSymbols
- should remove an identical consecutive characters that exceed the specified size
- should return empty string if it was passed to function like an argument
- should return empty string if "size" equal 0
- should return the same string if "size" parameter wasn't specified
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

2020-12-21 08:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
trimSymbols
- should remove an identical consecutive characters that exceed the specified size
- should return empty string if it was passed to function like an argument
- should return empty string if "size" equal 0
- should return the same string if "size" parameter wasn't specified
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

2020-12-21 12:14 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-12-22 11:50 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        return path.split(".").reduce(function(result, key) {
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2020-12-22 11:51 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +                return undefined;
мы не работаем с `undefined` напрямую, поэтому достаточно просто `return`

2020-12-22 11:51 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +    return Array.from(new Set([...arr]));
достаточно просто `return [...new Set(arr)]`

2020-12-22 11:52 UTC, dosandk requested changes
необходимо поправить решение `createGetter`

2020-12-22 13:45 UTC, alekseipeecho commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +                return undefined;
done

2020-12-22 13:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-24 13:23 UTC, dosandk commented
@alekseipeecho уточните пожалуйста первая задача, которая непонятна, это `createGetter`, если да, то какие именно моменты не были понятны?
Достаточно ли было разбора на занятии для того чтобы появилось понимание того как задачу решить?

2020-12-24 13:25 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    let arr = path.split(".");
`arr` - это `const`. Помните что переменная которую мы не переприваиваем, это всегда `const`

2020-12-24 13:25 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +        return undefined;
аналогичный комментарий как в решении `createGetter`. Достаточно просто `return` без `undefined`

2020-12-24 13:25 UTC, dosandk approved these changes

2020-12-24 13:26 UTC, merged