tooltip skip tests
js-tasks-ru/js-20201211_alexey-b pull request #6
Opened 2021-01-04 10:06 UTC by alekseipeecho

2021-01-04 10:13 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2021-01-04 16:14 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Tooltip компонент
+ should be rendered correctly
+ should be shown when moving over the element with data-tooltip attribute
+ should be hidden when moving out from the element with data-tooltip attribute
+ should have ability to be destroyed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2021-01-07 13:14 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +        if (event == '') {
в каком случае в данный метод может попасть аргумент `event` со значением пустой строки?
и напомню что `==` нет в JS

2021-01-07 13:15 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +        if (event.target.dataset.tooltip != undefined) {
и такого оператора тоже нет `!=`

2021-01-07 13:15 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +        if (event.target.dataset.tooltip != undefined) {
в каком случае `event` будет равен `undefined`?

2021-01-07 13:16 UTC, dosandk requested changes
необходимо дать ответы на вопросы

2021-01-07 15:41 UTC, alekseipeecho commented on 06-events-practice/2-tooltip/index.js
> +        if (event == '') {
Это сделано для того чтобы прошел тест  tooltip.render('');  Вижу что не правильно понял тест.

2021-01-10 14:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-01-10 18:14 UTC, dosandk approved these changes
good 👍

2021-01-10 18:15 UTC, merged